project_id = "nqrwtihwuvyfucmbcsem"

[functions.database-backup]
verify_jwt = true

[functions.kpi-daily-snapshot]
verify_jwt = false

[functions.kpi-email-digest]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.xray-stream]
verify_jwt = false

[functions.xray-analyze]
verify_jwt = false

[functions.bulk-password-reset]
verify_jwt = false
