// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqrwtihwuvyfucmbcsem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xcnd0aWh3dXZ5ZnVjbWJjc2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjA2NjEsImV4cCI6MjA2OTYzNjY2MX0.nsj54ja-75ePDqhUJKFUTQJbBxavir9YhSdDrnWiekc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});